config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'

  resources :users, only: [] do
    collection do
      get :hosted_events
      get :attendent_events
    end
  end

  resources :events do
    member do
      post :join
      delete :leave
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances, source: :attendee
  validates :name, presence: true
  validate :date_in_future

  scope :past, -> { where('date < ?', Date.today) }
  scope :future, -> { where('date >= ?', Date.today) }

  private

  def date_in_future
    return unless date.present? && date < Date.today

    errors.add(:date, 'Must be in the future')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id'
  has_many :attendances, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendances, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy join leave]
  def index
    @events = Event.page(params[:page])
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @event.destroy
      redirect_to root_path, notice: 'Event deleted.'
    else
      render :index, status: :unprocessable_entity
    end
  end

  def join
    event_attendance = @event.attendances.new(attendee: current_user)
    if event_attendance.save
      redirect_to @event, notice: 'You have successfully joined the event.'
    else
      redirect_to @event, status: :unprocessable_entity
    end
  end

  def leave
    attendance = current_user.attendances.find_by(event: @event)
    return unless attendance.destroy

    redirect_to @event, notice: 'You have successfully left the event.'
  end

  private

  def set_event
    @event = Event.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Event not found.'
    redirect_to events_path
  end

  def event_params
    params.require(:event).permit(:name, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def hosted_events
    hosted_events = current_user.created_events.includes(:creator)
    @hosted_events = hosted_events.page(params[:page])
  end

  def attendent_events
    attendent_events = Event.joins(:attendances).where(attendances: { attendee: current_user })
    @past_events = attendent_events.past.order(date: :desc).page(params[:page])
    @upcoming_events = attendent_events.future.order(date: :asc).page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <%= render partial: 'layouts/shared/error_messages', locals: { object: event } %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, class: "form-control" %>
  </div>

  <%= yield(form) %>
<% end %>

app/views/events/_list_events.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Date</th>
      <% if show_actions %>
        <th scope="col">Action</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% events.each do |event| %>
      <tr scope="row">
        <td><%= link_to event.name, event_path(event), style: "text-decoration: none;" %></td>
        <td><%= event.date %></td>
        <% if show_actions %>
          <td>
            <%= link_to 'Edit', edit_event_path(event), class: 'btn btn-primary' %>
            <%= link_to "Delete", event_path(event), data: { turbo_method: :delete }, class: "btn btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/edit.html.erb
<div class="container">
  <h3 class='pt-4 mb-4'>Edit Event</h3>
  <%= render 'event_form', event: @event do |f| %>
    <%= f.submit "Update Event", class: "btn btn-primary mt-3" %>
    <%= link_to "Back", :back, style: "text-decoration: none;",  class: "btn btn-secondary mt-3" %>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="container">
  <h3 class='pt-4 mb-4'>All Events</h3>
  <%= render 'list_events', events: @events, show_actions: false %>
</div>
<%= render partial: 'layouts/shared/pagination', locals: { collection: @events } %>

app/views/events/new.html.erb
<div class="container">
  <h3 class='pt-4 mb-4'>Add New Event</h3>
  <%= render 'event_form', event: @event do |f| %>
    <%= f.submit "Create Event", class: "btn btn-primary mt-3" %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container pt-4">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title"><%= @event.name %></h1>
      <p class="card-text"><strong>Event Date:</strong> <%= @event.date.strftime('%B %d, %Y') %></p>
      <hr>
      <h4 class="mt-4">Attendees</h4>
      <div class="card-text">
        <ul>
          <% @event.attendees.each do |attendee| %>
            <li><%= attendee.email %></li>
          <% end %>
        </ul>
      </div>

      <div class="text-end">
        <%= link_to "Back", root_path, style: "text-decoration: none;",  class: "btn btn-secondary me-2" %>
        <% if current_user && current_user.attendances.exists?(event_id: @event.id) %>
          <%= link_to "Leave", leave_event_path(@event), data: { turbo_method: :delete }, class: "btn btn-danger" %>
        <% else %>
          <%= link_to "Join", join_event_path(@event), data: { turbo_method: :post }, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container-flouid">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">
        <h3>Event Manager</h3>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
          <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Events
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><%= link_to "Attended Events", attendent_events_users_path, class: "nav-link active" %></li>
                <li><%= link_to "Hosted Events", hosted_events_users_path, class: "nav-link active" %></li>
                <li><%= link_to "Add New Event", new_event_path, class: "nav-link active" %></li>
              </ul>
            </li>
          <% end %>
        </ul>
        <form class="">
          <% if current_user %>
            <%= link_to "Logout", destroy_user_session_path, class: 'btn btn-outline-primary mr-2', method: :delete, data: { turbo_method: :delete }  %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: 'btn btn-outline-primary mr-2' %>
            <%= link_to "Register", new_user_registration_path, class: 'btn btn-outline-success' %>
          <% end %>
        </form>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <%= render 'layouts/header' %>
  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/shared/_pagination.html.erb
<div class="container pagination justify-content-center">
  <%= paginate collection, theme: 'bootstrap-5' %>
</div>

app/views/users/attendent_events.html.erb
<div class="container">
  <h3 class='pt-4 mb-4'>Attendent Events</h3>
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Past Events</h5>
            <% unless @past_events.nil? || @past_events.empty?  %>
              <%= render 'events/list_events', events: @past_events, show_actions: false %>
              <%= render partial: 'layouts/shared/pagination', locals: { collection: @past_events } %>
            <% else %>
              <p>You don't have any events in past</p>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Upcoming Events</h5>
            <% unless @upcoming_events.nil? || @upcoming_events.empty? %>
              <%= render 'events/list_events', events: @upcoming_events, show_actions: false %>
              <%= render partial: 'layouts/shared/pagination', locals: { collection: @upcoming_events } %>
            <% else %>
              <p>You don't have any upcoming events</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/users/hosted_events.html.erb
<div class="container">
  <h3 class='pt-4 mb-4'>Hosted Events</h3>
  <%= render 'events/list_events', events: @hosted_events, show_actions: true %>
</div>
<%= render partial: 'layouts/shared/pagination', locals: { collection: @hosted_events } %>